### ISSUE TITLE
Fail to install with python 3.5

### ISSUE THREAD

**Issue by Jenselme** [jedie/python-creole#28]
Hi,

I just tried to install python-creole with `pip install creole` on python 3.5 and I get this error message:

```
Collecting creole
  Using cached creole-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cpqal4_a/creole/setup.py", line 4, in <module>
        import creole
      File "/tmp/pip-build-cpqal4_a/creole/creole/__init__.py", line 28, in <module>
        from creole.rules import Rules
      File "/tmp/pip-build-cpqal4_a/creole/creole/rules.py", line 144
        self.wiki = ur'''(?P<wiki>[%s]\w+[%s]\w+)''' % (up_case, up_case)
                                                   ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cpqal4_a/creole
```

**Comment by Jenselme** [comment]
I just didn't use the right project. I wanted `pip install python-creole` which work perfectly. My apologizes.
