### ISSUE TITLE
Test failures for Python 3.6

### ISSUE THREAD

**Issue by jugmac00** [jedie/python-creole#32]
```
python3 -m venv venv
. venv/bin/activate
pip install nose

python setup.py nosetests

...
FAIL: test_creole2html (creole.tests.test_cli.CreoleCLITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jugmac00/Projects/python-creole/creole/tests/test_cli.py", line 33, in test_creole2html
    cli_str="creole2html",
  File "/home/jugmac00/Projects/python-creole/creole/tests/test_cli.py", line 86, in _test_convert
    verbose=False,
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 62, in assertSubprocess
    popen_args2, retcode2, stdout2 = self.subprocess(popen_args, verbose)
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 48, in subprocess
    self.fail("Error subprocess call with %r: %s" % (popen_args, err))
AssertionError: Error subprocess call with ['creole2html', '/tmp/tmppu8uj9b3', '/tmp/tmpvee3cf5j']: [Errno 2] No such file or directory: 'creole2html': 'creole2html'
    """Fail immediately, with the given message."""
>>  raise self.failureException("Error subprocess call with ['creole2html', '/tmp/tmppu8uj9b3', '/tmp/tmpvee3cf5j']: [Errno 2] No such file or directory: 'creole2html': 'creole2html'")
    

======================================================================
FAIL: test_html2creole (creole.tests.test_cli.CreoleCLITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jugmac00/Projects/python-creole/creole/tests/test_cli.py", line 40, in test_html2creole
    cli_str="html2creole",
  File "/home/jugmac00/Projects/python-creole/creole/tests/test_cli.py", line 86, in _test_convert
    verbose=False,
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 62, in assertSubprocess
    popen_args2, retcode2, stdout2 = self.subprocess(popen_args, verbose)
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 48, in subprocess
    self.fail("Error subprocess call with %r: %s" % (popen_args, err))
AssertionError: Error subprocess call with ['html2creole', '/tmp/tmp9k5nqo3f', '/tmp/tmpbfn54j47']: [Errno 2] No such file or directory: 'html2creole': 'html2creole'
    """Fail immediately, with the given message."""
>>  raise self.failureException("Error subprocess call with ['html2creole', '/tmp/tmp9k5nqo3f', '/tmp/tmpbfn54j47']: [Errno 2] No such file or directory: 'html2creole': 'html2creole'")
    

======================================================================
FAIL: test_html2rest (creole.tests.test_cli.CreoleCLITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jugmac00/Projects/python-creole/creole/tests/test_cli.py", line 51, in test_html2rest
    cli_str="html2rest",
  File "/home/jugmac00/Projects/python-creole/creole/tests/test_cli.py", line 86, in _test_convert
    verbose=False,
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 62, in assertSubprocess
    popen_args2, retcode2, stdout2 = self.subprocess(popen_args, verbose)
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 48, in subprocess
    self.fail("Error subprocess call with %r: %s" % (popen_args, err))
AssertionError: Error subprocess call with ['html2rest', '/tmp/tmpv0mbo16n', '/tmp/tmpja2_3n4v']: [Errno 2] No such file or directory: 'html2rest': 'html2rest'
    """Fail immediately, with the given message."""
>>  raise self.failureException("Error subprocess call with ['html2rest', '/tmp/tmpv0mbo16n', '/tmp/tmpja2_3n4v']: [Errno 2] No such file or directory: 'html2rest': 'html2rest'")
    

======================================================================
FAIL: test_html2textile (creole.tests.test_cli.CreoleCLITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jugmac00/Projects/python-creole/creole/tests/test_cli.py", line 58, in test_html2textile
    cli_str="html2textile",
  File "/home/jugmac00/Projects/python-creole/creole/tests/test_cli.py", line 86, in _test_convert
    verbose=False,
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 62, in assertSubprocess
    popen_args2, retcode2, stdout2 = self.subprocess(popen_args, verbose)
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 48, in subprocess
    self.fail("Error subprocess call with %r: %s" % (popen_args, err))
AssertionError: Error subprocess call with ['html2textile', '/tmp/tmpefk9xzdo', '/tmp/tmphbkeu11_']: [Errno 2] No such file or directory: 'html2textile': 'html2textile'
    """Fail immediately, with the given message."""
>>  raise self.failureException("Error subprocess call with ['html2textile', '/tmp/tmpefk9xzdo', '/tmp/tmphbkeu11_']: [Errno 2] No such file or directory: 'html2textile': 'html2textile'")
    

======================================================================
FAIL: test_version (creole.tests.test_cli.CreoleCLITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jugmac00/Projects/python-creole/creole/tests/test_cli.py", line 104, in test_version
    verbose=False,
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 62, in assertSubprocess
    popen_args2, retcode2, stdout2 = self.subprocess(popen_args, verbose)
  File "/home/jugmac00/Projects/python-creole/creole/tests/utils/unittest_subprocess.py", line 48, in subprocess
    self.fail("Error subprocess call with %r: %s" % (popen_args, err))
AssertionError: Error subprocess call with ['creole2html', '--version']: [Errno 2] No such file or directory: 'creole2html': 'creole2html'
    """Fail immediately, with the given message."""
>>  raise self.failureException("Error subprocess call with ['creole2html', '--version']: [Errno 2] No such file or directory: 'creole2html': 'creole2html'")
    

----------------------------------------------------------------------
Ran 236 tests in 1.254s

FAILED (failures=5)
```

**Comment by jedie** [comment]
python 3.6 is used in CI pipeline, see: https://travis-ci.org/jedie/python-creole/

So this should not happen.

However, the CI pipeline should be updated.

**Comment by jugmac00** [comment]
see pr #33

**Comment by jedie** [comment]
Yes, but the tests fail for another reason, see: https://travis-ci.org/jedie/python-creole/jobs/636364772 isn't it?

**Comment by jugmac00** [comment]
Hi Jens,
thank you for getting back to me so quickly.

I never ever used `nose`  before, so I am unfamiliar with its output.

But I get this output:
```
creole/tests/test_creole2html.py::TestCreole2html::test_code_macro
  /home/jugmac00/Projects/python-creole/creole/tests/test_creole2html.py:210: UserWarning: Skip test, because 'pygments' is not installed.
    warnings.warn("Skip test, because 'pygments' is not installed.")
```

So locally I do not execute the tests which fail on travis.

```
    def test_code_macro(self):
        if not PYGMENTS:
            # TODO: Use @unittest.skipIf if python 2.6 will be not support anymore
            warnings.warn("Skip test, because 'pygments' is not installed.")
            return
```

But it looks like I get other failures.


As a side note, I am quite happy to see that you still care about this project, although there was no commit for 2 years.

Ok, I found the reason for the failures - locally I have `docutils` not installed.

So the documentation could be updated:
https://github.com/jedie/python-creole#unittests

Also, I wonder whether `docutils` and `pygments` should be part of `setup.py`s `install_requires` or at least `extra_requires`.

**Comment by jedie** [comment]
This is obsolete, isn't it?

**Comment by jugmac00** [comment]
Yes, this is obsolete now. Thank you!
